### ISSUE TITLE
Parser implementation WBS

### ISSUE THREAD

**Issue by magicant** [magicant/flesh#47]
# Token
 
- [x] Single quotation #9
- [x] Double quotation #7
- [ ] (Tilde expansion)
- Parameter expansion
  - [x] Non-braced expansion #96
  - [ ] Braced expansion
  - [ ] Prefix
  - [ ] Index (non-POSIX)
  - Modifier
    - [ ] `-` `+` `=` `?`
    - [ ] `#` `%`
    - [ ] Substitution (non-POSIX)
- Command substitution
  - [x] Backquote syntax #63
  - [x] `$()` syntax #48
- [x] Arithmetic expansion #66
- [ ] (Brace expansion (non-POSIX))
- Alias
  - [x] Simple substitution #13
  - [x] Preventing recursion #25
  - [x] Substituting next token after blank-ending alias #54
  - [ ] Global alias (non-POSIX)

# Syntax

- [x] Complete line #24
- [x] Compound list #42
- [x] And-or list #22
- [x] Pipeline #21
- Command
  - Simple command
    - [x] Command word ~~#11~~ #42
    - [x] Redirection ~~#19~~ #42
    - [x] Assignment #71
  - Compound command
    - [x] Grouping #42
    - [x] Subshell #46
    - [x] For #73
    - [x] Case #95
    - [x] If #69
    - [x] While & until #59
    - [x] Redirection #45
  - Function definition
    - [x] Bourne-style (without keyword) #92
    - [ ] Ksh-style (with keyword, non-POSIX)
- Redirect
  - [x] `<` `<>` `>` `>>` `>|` `<&` `>&` #51
  - Here document
    - [x] Operator #19
    - [x] Expanded content #27
    - [x] Literal content #28
  - [ ] Here string (non-POSIX)

# Miscellaneous

- [ ] Converting `UnknownReason` to human-friendly error message
