### ISSUE TITLE
Alias substitution following blank-ending alias

### ISSUE THREAD

**Issue by magicant** [magicant/flesh#54]
As defined in POSIX, any word token is subject to alias substitution if it follows another alias substitution that ends with a blank. To support this feature, the parser monad needs to be redefined.

- [x] Redefine `MonadInput` to remember if an upcoming token should be subjected to alias substitution. #56, #57
- [x] Apply alias substitution according to the new `MonadInput` definition. #58
- ~~Forget the blank-ending alias on a newline token.~~
- [x] Use the new alias/word parser for parsing syntax constructs. #58
