### ISSUE TITLE
Refining alias handling monad

### ISSUE THREAD

**Issue by magicant** [magicant/flesh#77]
#75 made `AliasT` a true monad, and we can refactor it even more.

- [ ] Test: Don't reparse substituted token.
- [x] Make most parsers in Flesh.Language.Parser.Syntax just monads rather than `AliasT`. #79
- [x] Consider hiding `getAliasT`. #79
- [x] Consider renaming `AliasT` to `ReparseT`. #80
- [ ] Make `substituteAlias` a monad class method. (https://github.com/magicant/flesh/issues/74#issuecomment-349951718)
  - Move `MonadParser` and `ParserT` to Flesh.Language.Parser.Class`.
  - Replace `MonadReader` with `MonadAlias` as a superclass of `MonadParser`.

**Comment by magicant** [comment]
Making `subsituteAlias` a monad class method is no longer a valid idea. Instead we could reconstruct `MonadParser` from more fine-grained monad transformers:

```haskell
class Monad m => MonadInput m where
  popChar :: m (Either Position (Positioned Char))
  lookahead :: m a -> m a
  peekChar :: m (Either Position (Positioned Char))
  currentPosition :: m Position

class Monad m => MonadInputRecord where
  reverseConsumedChars :: m [Positioned Char]

class Monad m => MonadReparse where
  maybeReparse :: m (Maybe [Positioned Char], a) -> m a

class Monad m => MonadContext where
  definitionFor :: Text -> MaybeT m Definition

class (
  MonadInput m,
  MonadInputRecord m,
  MonadReparse m,
  MonadContext m,
  MonadError Failure m,
  MonadPlus m)
  => MonadParser m
```

```haskell
newtype ParserT m a = ParserT (m a)
instance (
  MonadInput m,
  MonadInputRecord m,
  MonadReparse m,
  MonadContext m,
  MonadError Failure m)
    => MonadParser (ParserT m)
```

**Comment by magicant** [comment]
Making `subsituteAlias` a monad class method is no longer a valid idea. Instead we could reconstruct `MonadParser` from more fine-grained monad transformers:

```haskell
class Monad m => MonadInput c m where
  beginning :: c
  readAt :: c -> m (Either Position (c, Positioned Char))

class Monad m => MonadBuffer m where -- currently known as MonadInput
  popChar :: m (Either Position (Positioned Char))
  lookahead :: m a -> m a
  peekChar :: m (Either Position (Positioned Char))
  currentPosition :: m Position

class Monad m => MonadReparse where
  maybeReparse :: m (Maybe [Positioned Char], a) -> m a

class Monad m => MonadRecord where -- currently known as MonadInputRecord
  reverseConsumedChars :: m [Positioned Char]

class (
  MonadBuffer m,
  MonadReparse m,
  MonadRecord m,
  MonadReader DefinitionSet m,
  MonadError Failure m,
  MonadPlus m)
    => MonadParser m
```

```haskell
instance MonadInput      ...

newtype ExceptT e m a = ExceptT (m (Either e a))
instance MonadInput      (ExceptT ...)
instance MonadError ...  (ExceptT ...)
m (Either F a)

newtype CursorT c m a = CursorT (StateT c m a)
instance MonadError ...  (CursorT ...)
instance MonadBuffer     (CursorT ...)
c -> m (Either F (a, c))

newtype PushBackT m a = PushBackT (StateT [Positioned Char] m a)
instance MonadError ...  (PushBackT ...)
instance MonadBuffer     (PushBackT ...)
instance MonadReparse    (PushBackT ...)
[PC] -> c -> m (Either F (a, [PC], c))

newtype ReparseT m a = ReparseT (m (Maybe (Maybe (ReparseT m a), a)))
instance MonadError ...  (ReparseT ...)
instance MonadBuffer     (ReparseT ...)
instance MonadReparse    (ReparseT ...)
[PC] -> c -> m (Either F (Maybe (Maybe ..., a), [PC], c))

newtype RecordT m a = RecordT (StateT [Positioned Char] m a)
instance MonadError ...  (RecordT ...)
instance MonadBuffer     (RecordT ...)
instance MonadReparse    (RecordT ...)
-- instance MonadReader ... (RecordT ...)
instance MonadRecord     (RecordT ...)
[PC] -> [PC] -> c -> m (Either F (Maybe (Maybe ..., a, [PC]), [PC], c))

newtype ReaderT r m a = ReaderT (r -> m a)
instance MonadError ...  (ReaderT ...)
instance MonadBuffer     (ReaderT ...)
instance MonadReparse    (ReaderT ...)
instance MonadReader ... (ReaderT ...)
instance MonadRecord ... (ReaderT ...)
DS -> [PC] -> [PC] -> c -> m (Either F (Maybe (Maybe ..., a, [PC]), [PC], c))

newtype ParserT m a = ParserT (m a)
instance MonadError ...  (ParserT ...)
instance MonadBuffer     (ParserT ...)
instance MonadReparse    (ParserT ...)
instance MonadReader ... (ParserT ...)
instance MonadRecord     (ParserT ...)
instance MonadPlus       (ParserT ...)
instance MonadParser     (ParserT ...)
```

**Comment by magicant** [comment]
Continued to #81.
